<?php

namespace AppBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{

    public function search($motsCle)
    {
        $query = $this->createQueryBuilder('a')
            ->where('a.titre like :titre')
            ->setParameter('titre', $motsCle . "%")
            ->orderBy("a.titre", "ASC")
            ->getQuery();

            return $query->getResult();
    }
    
}
