<?php

namespace AppBundle\Repository;

/**
 * TypeAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAnnonceRepository extends \Doctrine\ORM\EntityRepository
{
}
